version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "sbt"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    groups:
      sbt:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/rust-compose/rust-greeter"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    groups:
      cargo:
        patterns:
          - "*"
